project_id = "mrtovhqequmhdgccwffs"

[functions.validate-invitation]
verify_jwt = false  # Allow anonymous users to validate invitation tokens

[functions.ping-handler]
verify_jwt = false

[functions.send-failure-email]
verify_jwt = false

[functions.send-slack-notification]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false